.lgtm.yml

exclude some files from lgtm #18

---

package-lock.json
src/compiler/Compiler.js
src/compiler/JSRuntimeTemplate.js
test/runtime_test.js

runtime's main function should be async #26

---

src/compiler/JSCodeGenVisitor.js
test/compiler_test.js
test/interpreter_test.js
test/specs/attribute_spec.txt
test/specs/call_spec.txt
test/specs/context_spec.txt
test/specs/element_spec.txt
test/specs/format_spec.txt
test/specs/list_spec.txt
test/specs/simple_spec.txt
test/specs/tst_spec.txt
test/specs/uri_spec.txt
test/specs/use_spec.txt

Before going forward with other unit tests, I'd be glad to get some feedback for the proposed spec change for #28 .

Create unit tests for sourcemaps #28

---

src/compiler/Compiler.js
test/runtime_test.js

Extra platform-dependent slash detected

Tests fail on Windows 7x64 #34

---

src/main.js
src/parser/htl/nodes/Interpolation.js
src/parser/html/MarkupHandler.js
test/engine_test.js
test/html_parser_test.js

Performance improvements

---

src/compiler/Compiler.js
src/compiler/ExpressionFormatter.js
src/compiler/JSCodeGenVisitor.js
src/parser/commands/TemplateReference.js
src/parser/plugins/UsePlugin.js
src/runtime/Runtime.js
test/compiler_test.js
test/interpreter_test.js
test/specs/template_spec.js
test/specs/template_spec.txt
test/specs/template_spec/templateLib.html

fix(compiler): use statement cannot load external templates

---

src/parser/html/MarkupHandler.js
src/parser/plugins/UnwrapPlugin.js
test/specs/template_spec.txt
test/specs/unwrap_spec.js
test/specs/unwrap_spec.txt

implement support for data-sly-unwrap

---

src/parser/plugins/CallPlugin.js
test/specs/call_spec.txt
test/specs/template_spec.txt

fix(call): do not unwrap call element

---

src/runtime/xss_api.js
test/runtime_test.js
test/specs/context_spec.js
test/specs/context_spec.txt
test/templates/xss.htl
test/templates/xss.html

fix(xss): regression in uri sanitizer

---

src/compiler/Compiler.js
src/parser/html/MarkupHandler.js
src/parser/html/TemplateParser.js
test/runtime_test.js
test/templates/xss_unsafe.html

feat(compiler): allow to set default context

---

src/runtime/VDOMFactory.js
test/specs/dom_spec.js
test/specs/dom_spec_jsd.txt

feat(dom): allow injection of ${document.body} anywhere

---

src/runtime/VDOMFactory.js
src/runtime/format_xss.js
test/specs/dom_spec.js
test/specs/dom_spec_hast.txt
test/specs/dom_spec_jsd.txt

fix(dom): be more lenient when adding arrays

---

src/compiler/ExpressionFormatter.js
src/compiler/JSCodeGenVisitor.js
src/compiler/JSCodeTemplate.js
src/compiler/JSRuntimeTemplate.js
src/parser/commands/Loop.js
src/parser/plugins/ListPlugin.js
src/runtime/Runtime.js
test/specs/dom_spec.js
test/specs/dom_spec_jsd.txt
test/templates/custom_template.js

feat(dom): add support for nodelist iteration

---

.circleci/config.yml

Use CircleCI for Windows Builds

---

PULL_REQUEST_TEMPLATE.MD

I have added the common Adobe `PULL_REQUEST_TEMPLATE.MD` to this repository.
Now contributors will get this whilst submitting a PR :-
```
```

Initialised the Adobe PULL_REQUEST_TEMPLATE.MD

---

src/compiler/DomHandler.js
test/specs/template_spec.js
test/specs/template_spec.txt
test/specs/template_spec/button.htl
test/specs/template_spec/heading.htl
test/specs/template_spec/library.htl
test/specs/template_spec_hast.txt

fixes an issue where function names for template were not properly formatted.

fix(template): ensure correct template function names

---

src/parser/commands/CommandStream.js
test/specs/call_spec.txt
test/specs/template_spec.txt

fix(compiler): avoid writing if(false) blocks

---

src/compiler/Compiler.js
src/parser/commands/TemplateReference.js
src/parser/plugins/UsePlugin.js
src/runtime/Runtime.js
test/specs/call_spec.txt
test/specs/call_spec_hast.txt
test/specs/use_spec.txt
test/specs/use_spec_hast.txt

fix(compiler): use node require semantics for importing use classes

---

src/compiler/Compiler.js
test/compiler_test.js
test/templates/custom_modules/exp.js
test/templates/custom_modules/src.htl

feat(compiler): add support for custom import module statements 

---

src/runtime/format.js
test/specs/format_spec.js
test/specs/format_spec.txt
test/specs/format_spec_hast.txt

fix(format): use correct date format

---

src/compiler/JSCodeGenVisitor.js
src/parser/commands/Loop.js
src/parser/html/MarkupHandler.js
src/parser/plugins/RepeatPlugin.js
src/runtime/Runtime.js
test/specs/repeat_spec.js
test/specs/repeat_spec.txt

fix(repeat): implement data-sly-repeat

---

src/compiler/Compiler.js
src/compiler/JSCodeTemplate.js
src/compiler/JSRuntimeTemplate.js
test/specs/attribute_spec.txt
test/specs/call_spec.txt
test/specs/context_spec.txt
test/specs/element_spec.txt
test/specs/list_spec.txt
test/specs/simple_spec.txt
test/specs/template_spec.txt
test/specs/template_spec/template.htl
test/specs/tst_spec.txt
test/specs/uri_spec.txt
test/specs/use_spec.txt
test/templates/custom_modules/exp.js

fix(htl): ensure that templates have access to global variables

---

src/runtime/VDOMFactory.js
test/compiler_test.js
test/templates/fragment.htl
test/templates/fragment_body.html
test/templates/fragment_frag.html

feat(vdom): add option to suppress automatic body generation

---

src/runtime/xss_api.js
test/runtime_test.js
test/templates/xss.htl
test/templates/xss.html
test/templates/xss_unsafe.html

fixes #183
(not covering `srcset` checking)

fix(xss): test xss against original form

---

src/runtime/Runtime.js

This pull request does not add magic getters for Internet Explorer 11 in order to fix for `unhandled promise rejection referenceerror 'proxy' is undefined`.
#205 
This code has be tested in a local setup on Internet Explorer 11 using https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

feat(runtime): Add support for Internet Explorer 11

---

src/runtime/HtmlDOMFactory.js
src/runtime/VDOMFactory.js
test/runtime_test.js

fix(runtime): runtime cannot be executed twice

---

src/runtime/format_uri.js
test/specs/attribute_spec.txt

fixes #221
same as #222 but with test and proper code style.

fix(uri): undefined uri

---

src/compiler/Compiler.js
src/compiler/ExpressionFormatter.js
src/compiler/ExternalTemplateLoader.js
src/compiler/JSCodeTemplate.js
src/compiler/JSPureTemplate.js
src/compiler/JSRuntimeTemplate.js
test/specs/attribute_spec.txt
test/specs/call_spec.txt
test/specs/context_spec.txt
test/specs/element_spec.txt
test/specs/list_spec.txt
test/specs/simple_spec.txt
test/specs/template_spec.txt
test/specs/tst_spec.txt
test/specs/uri_spec.txt
test/specs/use_spec.txt
test/templates/custom_modules/exp.js
test/templates/custom_template.js

fixes #234
BREAKING CHANGE: $.slyResource was renamed to $.resource

feat(code): simplify code

---

src/index.js

feat(index): export script resolver

---

package-lock.json

Related to: https://github.com/adobe/htlengine/network/alert/package-lock.json/dot-prop/closed
Ran `npm audit fix` on master checkout.

chore(deps): bump dot-prop and minimist

---

src/compiler/Compiler.js
src/compiler/ExpressionFormatter.js
src/parser/commands/VariableBinding.js
src/parser/plugins/IncludePlugin.js
src/parser/plugins/ListPlugin.js
src/parser/plugins/ResourcePlugin.js
src/parser/plugins/UnwrapPlugin.js
src/parser/plugins/UsePlugin.js
test/specs/set_spec.txt
test/specs/tst_spec.txt
test/specs/use_spec.txt

fix(htl): toplevel properties are case insensitive

---

.github/workflows/semantic-release.yaml
src/compiler/Compiler.js

fix(win): fix 'require' problems on windows

---

src/parser/plugins/TestPlugin.js
test/specs/tst_spec.txt

fix(htl): data-sly-test problem with upper case characters

---

src/parser/html/MarkupHandler.js
src/parser/html/Plugin.js
src/parser/plugins/SetPlugin.js
src/parser/plugins/TestPlugin.js
test/specs/set_spec.txt
test/specs/tst_spec.txt

fix problems with data-sly-test and data-sly-set

---

src/runtime/Runtime.js
test/specs/list_spec.js
test/specs/list_spec.txt

fix(runtime): fix type error with lists

---

.circleci/config.yml
.nycrc.json
package-lock.json
package.json
src/compiler/DomHandler.js
src/compiler/JSCodeGenVisitor.js
test/compiler_test.js
test/specs/template.spec

fix(use): data-sly-use with same variable gives error

---

src/compiler/DomHandler.js
src/parser/plugins/TemplatePlugin.js
test/specs/template.spec

fix(compiler): ensure template variables are case insensitive

---

package-lock.json
package.json
src/runtime/Runtime.js
test/specs/template.spec
test/specs/template_spec/lv/item.htl
test/specs/template_spec/lv/itemContent.htl

fix(compiler): regession with camelcased template names

---

test/specs/template.spec
test/specs/template_spec/primaryButton.htl

add another case-insensitivity test.
fixes #301

chore(test): add more template tests

---

src/compiler/DomHandler.js
src/parser/plugins/TemplatePlugin.js
src/runtime/Runtime.js

fix(compiler): don't use javascrip Proxy
